
services:
  nexus:
    image: sonatype/nexus3:3.72.0
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    expose:
      - "8081"
      - "5000"
    # No ports exposed; Nginx will handle all traffic
    networks:
      - nexus-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - nexus
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/ssl
    networks:
      - nexus-network
volumes:
  nexus-data:
    driver: local
networks:
  nexus-network:
    driver: bridge


